## 전치 연산

2차원 배열의 전치(transpose) 연산은 행과 열을 바꾸는 작업입니다.

이는 배열의 T 속성으루 구할 수 있고 메서드가 아닌 속성이라는 점에 유의해야 합니다.

In [39]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## 배열의 크기 변형

만들어진 배열의 내부 데이터는 보존한 채로 형태만 바꾸려면 `reshape` 명령이나 메서드를 사용합니다.

예를 들어 12개의 원소를 가진 1차원 행렬은 3x4 형태의 2차원 행렬로 만들 수 있습니다.

In [41]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

사용하는 원소의 갯수가 정해져 있기 떄문에 `reshape` 명령의 형태인 튜플의 원소 중 하나는 -1 이라는 숫자로 대체할 수 있습니다.

-1을 넣으면 해당 숫자는 자동으로 나머지 차원의 크기를 계산해 넣게 됩니다.

In [43]:
# 첫번쨰 파라미터 : 첫번째 차원의 크기
# 두번쨰 파라미터 : 자동으로 나머지 차원의 크기를 계산하라는 의미의 -1
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
# 첫번쨰 차원의 크기 2로 고정
# 두번쨰 차원의 크기도 2로 고정
# 나머지 차원의 크기 자동 계산 : 12 / (2 * 2) = 3
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [45]:
# 첫번쨰 차원의 크기 2로 고정
# 자동 계산 : 12 / (2 * 2) = 3
# 3번쨰 배열의 원소 수 2로 고정
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

다차원 배열을 무조건 1차원으로 만들떄는 `flatten`이나 `ravel` 메서드를 사용합니다.

In [46]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

배열 사용에서 주의할 점은 길이가 5인 1차원 배열과 행렬의 개수가 (5,1)인 2차원 배열 또는

행열의 개수가 (1,5)인 2차원 배열은 데이터가 같아도 다른 객체라는 것에 주의가 필요합니다.

In [48]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [49]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [50]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [51]:
# :의 의미 = 마지막 x의 차원은 5, 이고 모든 행 선택
# np.newaxis = 새로운 축을 추가해 5, 에서 5,1 이 됨 -> [[0], [1], [2], [3], [4]]
# 즉 1차원 배열을 2차원 배열로 차원을 추가(np.newaxis)
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])