## 전치 연산

2차원 배열의 전치(transpose) 연산은 행과 열을 바꾸는 작업입니다.

이는 배열의 T 속성으루 구할 수 있고 메서드가 아닌 속성이라는 점에 유의해야 합니다.

In [3]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## 배열의 크기 변형

만들어진 배열의 내부 데이터는 보존한 채로 형태만 바꾸려면 `reshape` 명령이나 메서드를 사용합니다.

예를 들어 12개의 원소를 가진 1차원 행렬은 3x4 형태의 2차원 행렬로 만들 수 있습니다.

In [5]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

사용하는 원소의 갯수가 정해져 있기 떄문에 