## Numpy

Numpy는 수치 해석용 파이썬 패키지입니다.

다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용됩니다.

내부적으로는 BLAS 라이브러리와 LAPACK 라이브러리를 사용하고 있으며, C로 구현된 CPython에서만 사용할 수 있습니다.

<br>

넘파이의 배열 연산은 C로 구현된 내부 반복문을 이용하기 때문에 파이썬에 비해 속도가 빠르며,

벡터화 연산(vectorized operation)을 이용하여 간단한 코드로 복잡한 선형 대수 연산을 수행합니다.

또한 배열 인덱싱을 사용한 질의(Query) 기능을 이용하여 간단한 코드로도 복잡한 수식을 계산할 수 있습니다.

## 1차원 배열 생성

Numpy의 `array` 함수에 리스트를 넣으면 `ndarray` 클래스 객체 즉, 배열로 반환해 줍니다.

아래는 배열을 생성하는 방법입니다.

Python의 리스트와 비슷해보이지만, type 명령으로 자료형을 확인해보면 ndarray인 것을 알 수 있습니다.

In [574]:
import numpy
import numpy as np

ar = np.array([1,2,3,4,5,6,7,8,9,10])
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 벡터화 연산(vectorized operation)

배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산(vectorized operation)을 지원합니다.

예를 들어 여러개의 데이터를 모두 2를 곱해야 하는 상황일떄 for 반복문을 안쓰고 간단하게 각 원소에 곱할 수 있습니다.

In [575]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [576]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됩니다.

선형 대수에 적용되는 벡털화 연산에 대해서는 나중에 자세히 알아봅니다.

In [577]:
2 * a + b

array([12, 24, 36])

In [578]:
a == 2

array([False,  True, False])

In [579]:
b > 10

array([False,  True,  True])

In [580]:
(a == 2) & (b > 10)

array([False,  True, False])

## 2차원 배열 생성

ndarray는 N_dimensional Array의 약자입니다.

이름 그대로 1차원 배일 이외에도 2,3차원 등 다차원 배열 자료구조를 지원합니다.

아래 코드와 같이 리스트 내부에 리스트를 이용해 2차원 배열을 생성할 수 있습니다.

안쪽 리스트의 길이는 행렬의 열(가로) 개수, 바깥쪽 리스트의 길이는 행렬의 행(세로)의 개수가 됩니다.

예를 들어 2개의 행과 3개의 열을 가지는 2 x 3 배열은 다음과 같습니다.

In [581]:
c = np.array([[1,2,3], [4,5,6]]) # 2 x 3 array
c

array([[1, 2, 3],
       [4, 5, 6]])

2차원 배열의 행과 열의 개수는 다음과 같이 구합니다.

In [582]:
# 행의 개수
len(c)

2

In [583]:
# 열의 개수
len(c[0])

3

## 3차원 배열 생성

리스트의 리스트의 리스트를 이용하면 3차원 배열을 생성할 수 있습니다.

크기를 나타낼 떄는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시합니다.

예를 들어 2 x 3 x 4 배열은 다음과 같이 생성합니다.

In [584]:
# 2 x 3 x 4 array
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])

3차원 배열의 깊이, 행, 열은 다음과 같이 구할 수 있습니다.

In [585]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

## 배열의 차원과 크기 구하기

배열의 차원 및 크기를 구하는 더 간단한 방법은 배열의 `ndim` 속성과 `shape` 속성을 이용하는 것 입니다.

`ndim` 속성은 배열의 차원, `shape` 속성은 배열의 크기를 반환합니다.

In [586]:
a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [587]:
c = np.array([[1,2,3], [4,5,6]])
print(c.ndim)
print(c.shape)

2
(2, 3)


## 배열 슬라이싱

배열 객체로 구현한 다차원 배열의 원소 중 복수 개를 접근하려면 일반적인 파이썬 슬라이싱과 콤마를 함꼐 사용하면 됩니다.

In [588]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [589]:
# 첫번째 행 전체
a[0, :]

array([1, 2, 3])

In [590]:
# 두번쨰 열 전체
a[:, 1]

array([2, 5])

In [591]:
# 두번쨰 행의 두번째 열부터 끝 열까지
a[1, 1:]

array([5, 6])

In [592]:
# 처음 두 행과 처음 두 열
a[:2, :2]

array([[1, 2],
       [4, 5]])

## 배열 인덱싱

넘파이 배열 객체의 또다른 강력한 기능은 Fancy Indexing 이라고 부르는 배열 인덱싱 방법입니다.

이름은 인덱싱이지만 DB Query와 같은 기능을 수행합니다.

배열 인덱싱에서는 대괄호안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또다른 ndarray 배열을 받을 수 있습니다.

<br>

배열 인덱싱의 방식에는 Boolean 배열 방식과 정수 배열 방식 2가지가 있습니다.

### Boolean Indexing

- 인덱스 배열의 원소가 True, False 두 값으로만 구성됨
- 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 같아야 함

<br>

예를 들어 아래와 같은 1차원 `ndarray`에서 짝수인 원소만 골라내려면 짝수인 원소에 대응하는 인덱스 값이 True이고,

홀수인 원소에 대응하는 인덱스 값이 False인 인덱스 배열을 넣으면 됩니다.

In [593]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

### 정수 배열 Indexing

정수 배열 방식에서는 인덱스 배열의 원소 각각이 원래 `ndarray` 객체 원소 하나를 가리키는 인덱스 정수여야 합니다.

예를 들어 아래 1차원 배열에서 홀수번쨰 원소만 골라내려면 이렇게 하면 됩니다.

In [594]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

배열 인덱싱은 다차원 배열의 각 차원에도 사용할 수 있습니다.

In [595]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [596]:
# 모든 행의 특정 원소만 출력
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [597]:
# 인덱스의 행 순서를 바꿔서 출력
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])